version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db
    ports:
      - "5433:5432"
    networks:
      - custom

  test_db:
    container_name: "test_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db_test
    ports:
      - "5434:5432"
    networks:
      - custom

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - custom

networks:
  custom:
    driver: bridge
